package com.longer.springmvc.model;

public class Grade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.gradeId
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    private Integer gradeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.low
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    private Double low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.top
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    private Double top;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.name
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.gradeId
     *
     * @return the value of grade.gradeId
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public Integer getGradeid() {
        return gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.gradeId
     *
     * @param gradeid the value for grade.gradeId
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public void setGradeid(Integer gradeid) {
        this.gradeid = gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.low
     *
     * @return the value of grade.low
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public Double getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.low
     *
     * @param low the value for grade.low
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public void setLow(Double low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.top
     *
     * @return the value of grade.top
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public Double getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.top
     *
     * @param top the value for grade.top
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public void setTop(Double top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.name
     *
     * @return the value of grade.name
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.name
     *
     * @param name the value for grade.name
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}