package com.longer.springmvc.model;

public class Score {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.stu_no
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    private Integer stuNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.class_no
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    private Integer classNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.score
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.stu_no
     *
     * @return the value of score.stu_no
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public Integer getStuNo() {
        return stuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.stu_no
     *
     * @param stuNo the value for score.stu_no
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public void setStuNo(Integer stuNo) {
        this.stuNo = stuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.class_no
     *
     * @return the value of score.class_no
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public Integer getClassNo() {
        return classNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.class_no
     *
     * @param classNo the value for score.class_no
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public void setClassNo(Integer classNo) {
        this.classNo = classNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.score
     *
     * @return the value of score.score
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.score
     *
     * @param score the value for score.score
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}