package com.longer.springmvc.model;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_no
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    private Integer stuNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_name
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    private String stuName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_no
     *
     * @return the value of student.stu_no
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public Integer getStuNo() {
        return stuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_no
     *
     * @param stuNo the value for student.stu_no
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public void setStuNo(Integer stuNo) {
        this.stuNo = stuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_name
     *
     * @return the value of student.stu_name
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_name
     *
     * @param stuName the value for student.stu_name
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public void setStuName(String stuName) {
        this.stuName = stuName;
    }
}