package com.longer.springmvc.model;

public class Team {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.class_no
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    private Integer classNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.class_name
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.class_teacher
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    private String classTeacher;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.class_no
     *
     * @return the value of team.class_no
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public Integer getClassNo() {
        return classNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.class_no
     *
     * @param classNo the value for team.class_no
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public void setClassNo(Integer classNo) {
        this.classNo = classNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.class_name
     *
     * @return the value of team.class_name
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.class_name
     *
     * @param className the value for team.class_name
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.class_teacher
     *
     * @return the value of team.class_teacher
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public String getClassTeacher() {
        return classTeacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.class_teacher
     *
     * @param classTeacher the value for team.class_teacher
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    public void setClassTeacher(String classTeacher) {
        this.classTeacher = classTeacher;
    }
}