package com.longer.springmvc.mapper;

import com.longer.springmvc.model.Grade;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface GradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    int deleteByPrimaryKey(Integer gradeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    int insert(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    int insertSelective(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    Grade selectByPrimaryKey(Integer gradeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    int updateByPrimaryKeySelective(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    int updateByPrimaryKey(Grade record);
}