package com.longer.springmvc.mapper;

import com.longer.springmvc.model.Student;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    int deleteByPrimaryKey(Integer stuNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    Student selectByPrimaryKey(Integer stuNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    int updateByPrimaryKey(Student record);
}