package com.longer.springmvc.mapper;

import com.longer.springmvc.model.Team;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    int deleteByPrimaryKey(Integer classNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    int insert(Team record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    int insertSelective(Team record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    Team selectByPrimaryKey(Integer classNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    int updateByPrimaryKeySelective(Team record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team
     *
     * @mbggenerated Sun Dec 01 12:15:17 CST 2019
     */
    int updateByPrimaryKey(Team record);
}