package com.longer.springmvc.service;

import com.longer.springmvc.model.Score;

import java.util.List;

public interface ScoreService  {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Sun Dec 01 11:21:31 CST 2019
     */
    int insert(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Sun Dec 01 11:21:31 CST 2019
     */
    int insertSelective(Score record);

    List<Score> findMax();
}